#!/usr/bin/env python3
"""Generate the CJK chat-prose stylesheet and its ZhenKai subsets.

`app/fonts-content-cjk.css` and `public/fonts/lxgw-zhenkai/*` are generated;
`scripts/lxgw-content-cjk-slices.json` is the source of truth for the
`unicode-range` slices both weight bands mirror. The node tests
(`app/fonts-content-cjk.test.mjs`, `public/fonts-selfhosted.test.mjs`) guard the
generated shape, this script makes it reproducible:

  --check             fail if the committed CSS, subsets or manifest drifted
  --css               rewrite app/fonts-content-cjk.css from the manifest
  --subsets [--ttf F] rebuild public/fonts/lxgw-zhenkai/ + SHA256SUMS.txt
  --all    [--ttf F]  --css and --subsets together
  --slices-from F     rewrite the manifest's slice list from a WenKai stylesheet

The WenKai slices are not rebuilt here: they are vendored verbatim from
lxgw-wenkai-screen-webfont@1.7.0 (see public/fonts/lxgw-wenkai-screen/NOTICE.txt)
and the manifest was extracted from that package's `lxgwwenkaiscreen.css`.

Rebuilding subsets needs fonttools (which needs brotli for woff2 output):

  python3 -m venv .venv && .venv/bin/pip install fonttools brotli
  .venv/bin/python scripts/build-content-cjk-fonts.py --all
"""
from __future__ import annotations

import argparse
import concurrent.futures
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "scripts" / "lxgw-content-cjk-slices.json"
CSS = ROOT / "app" / "fonts-content-cjk.css"
WENKAI_DIR = ROOT / "public" / "fonts" / "lxgw-wenkai-screen"
ZHENKAI_DIR = ROOT / "public" / "fonts" / "lxgw-zhenkai"

FAMILY = "PiWebBodyCJK"
WENKAI_PREFIX = "lxgwwenkaiscreen-subset-"
ZHENKAI_PREFIX = "lxgwzhenkaigb-subset-"

# `local()` names per band: family name first, then the PostScript name, so a
# locally installed face wins before the self-hosted bytes are fetched.
# ZhenKai also keeps the older release's names (see notion-restyle's mapping).
WENKAI_LOCALS = "local('LXGW WenKai GB Screen'), local('LXGWWenKaiGBScreen')"
ZHENKAI_LOCALS = (
    "local('LXGW ZhenKai GB'), local('LXGWZhenKaiGB'), "
    "local('LXGW Zhen Kai'), local('LXGWZhenKai-Regular')"
)

WENKAI_SOURCE = {
    "family": "LXGW WenKai Screen",
    "package": "lxgw-wenkai-screen-webfont@1.7.0",
    "slicesFrom": "https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.7.0/lxgwwenkaiscreen.css",
    "notice": "public/fonts/lxgw-wenkai-screen/NOTICE.txt",
}

# The pinned upstream release the vendored ZhenKai subsets are cut from.
ZHENKAI_SOURCE = {
    "family": "LXGW ZhenKai GB",
    "project": "lxgw/LxgwZhenKai",
    "release": "v0.825",
    "asset": "LXGWZhenKaiGB-Regular.ttf",
    "url": "https://github.com/lxgw/LxgwZhenKai/releases/download/v0.825/LXGWZhenKaiGB-Regular.ttf",
    "sha256": "40876902a7ce25268ab710ad8fe6e2b63bc002aa4b68d22fd45fc1243726ced5",
    "bytes": 17545474,
}

HEADER = """/*
 * CJK faces for `--font-content`, the chat prose stack.
 *
 * GENERATED by `scripts/build-content-cjk-fonts.py` from
 * `scripts/lxgw-content-cjk-slices.json`. Edit those files, not this one
 * (`--check` fails when they drift).
 *
 * One role-named family, `PiWebBodyCJK`, carries both weight bands, so a single
 * `font-family` entry covers CJK at every weight:
 *
 *   font-weight 400      -> LXGW WenKai Screen (霞鹜文楷屏幕阅读版)
 *   font-weight 501 900  -> LXGW ZhenKai GB (霞鹜臻楷 GB)
 *
 * WenKai is the body face and ships a single weight, so bold CJK used to fall
 * back to Chromium's synthetic (stroked) bold. `.markdown-body` asks for 500
 * (WenKai band); headings, `strong` and list markers ask for 600/700 (ZhenKai
 * band). The two bands are separate `@font-face` rules inside ONE family --
 * that is what makes a weight request select a different face. Do not split
 * them into two families: font matching walks the stack family by family, so
 * the first family that covers the character wins and a separate bold family
 * would never be reached.
 *
 * `.markdown-body` also sets `font-synthesis-weight: none` (app/globals.css).
 * Chromium strokes its own synthetic bold onto any request of 600 or more
 * regardless of the declared weight range, which would double-bold ZhenKai.
 *
 * Each band prefers a locally installed font via `local()` -- the font stack
 * used to name "LXGW WenKai GB Screen" first -- and falls back to the
 * self-hosted subsets.
 *
 * Sources:
 *   - LXGW WenKai Screen: lxgw-wenkai-screen-webfont@1.7.0 ->
 *     public/fonts/lxgw-wenkai-screen/ (97 `unicode-range` slices).
 *   - LXGW ZhenKai GB: lxgw/LxgwZhenKai v0.825 `LXGWZhenKaiGB-Regular.ttf`,
 *     subsetted into the same 97 `unicode-range` slices ->
 *     public/fonts/lxgw-zhenkai/ (provenance in its NOTICE.txt).
 *
 * Only the family name, the per-subset `font-weight` and the `local()` sources
 * differ from the upstream stylesheets: every `unicode-range` is the WenKai
 * slice it mirrors, so both bands fetch exactly the same text ranges.
 */

/* === 常规字重：霞鹜文楷屏幕阅读版 === */
"""

WENKAI_BAND_COMMENT = "\n/* === 加粗字重（>500）：霞鹜臻楷 GB === */\n"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text())


def face_rule(comment: str, weight: str, locals_: str, url: str, ranges: str) -> str:
    return f"""/* {comment} */
@font-face {{
  font-family: '{FAMILY}';
  font-style: normal;
  font-weight: {weight};
  font-display: swap;
  src: {locals_}, url({url}) format('woff2');
  unicode-range: {ranges};
}}
"""


def css_text(manifest: dict) -> str:
    slices = manifest["slices"]

    def band(prefix: str, dirname: str, comment: str, weight: str, locals_: str) -> list[str]:
        return [
            face_rule(
                f"{comment} [{entry['subset']}]",
                weight,
                locals_,
                f"/fonts/{dirname}/{prefix}{entry['subset']}.woff2",
                entry["unicodeRange"],
            )
            for entry in slices
        ]

    wenkai = band(WENKAI_PREFIX, "lxgw-wenkai-screen", "LXGW WenKai Screen", "400", WENKAI_LOCALS)
    zhenkai = band(ZHENKAI_PREFIX, "lxgw-zhenkai", "LXGW ZhenKai GB", "501 900", ZHENKAI_LOCALS)
    return HEADER + "\n" + "\n".join(wenkai) + WENKAI_BAND_COMMENT + "\n" + "\n".join(zhenkai)


FACE_RE = re.compile(r"@font-face\s*\{(.*?)\}", re.S)


def parse_rules(text: str) -> list[dict]:
    rules = []
    for body in FACE_RE.findall(text):
        url = re.search(r"url\(\s*([^)]+?)\s*\)", body).group(1)
        rules.append(
            {
                "url": url,
                "family": re.search(r"font-family:\s*'([^']+)'", body).group(1),
                "weight": re.search(r"font-weight:\s*([^;]+);", body).group(1).strip(),
                "range": re.search(r"unicode-range:\s*([^\n;]+)", body).group(1).strip(),
            }
        )
    return rules


def slices_from(text: str, wanted_dir: str) -> list[dict]:
    """Slice list of the WenKai band, ordered by subset number."""
    entries = []
    for rule in parse_rules(text):
        match = re.search(rf"/fonts/{wanted_dir}/[a-z]+-subset-(\d+)\.woff2", rule["url"])
        if match:
            entries.append({"subset": int(match.group(1)), "unicodeRange": rule["range"]})
    if not entries:
        raise SystemExit(f"no /fonts/{wanted_dir}/ faces found; nothing to extract")
    entries.sort(key=lambda entry: entry["subset"])
    return entries


def check() -> int:
    manifest = load_manifest()
    problems: list[str] = []

    expected = css_text(manifest)
    actual = CSS.read_text()
    if actual != expected:
        for index, (want, got) in enumerate(zip(expected.splitlines(), actual.splitlines()), 1):
            if want != got:
                problems.append(f"{CSS.relative_to(ROOT)}:{index} drifted:\n  want {want}\n  got  {got}")
                break
        else:
            problems.append(f"{CSS.relative_to(ROOT)} has a different length than the manifest generates")

    for entry in manifest["slices"]:
        for directory, prefix in ((WENKAI_DIR, WENKAI_PREFIX), (ZHENKAI_DIR, ZHENKAI_PREFIX)):
            path = directory / f"{prefix}{entry['subset']}.woff2"
            if not path.is_file() or path.stat().st_size == 0:
                problems.append(f"missing or empty: {path.relative_to(ROOT)}")

    listed = {}
    for line in (ZHENKAI_DIR / "SHA256SUMS.txt").read_text().splitlines():
        if line.strip():
            digest, name = line.split()
            listed[name] = digest
    on_disk = sorted(path.name for path in ZHENKAI_DIR.glob("*.woff2"))
    if sorted(listed) != on_disk:
        problems.append("public/fonts/lxgw-zhenkai/SHA256SUMS.txt does not list exactly the shipped subsets")
    for name, digest in listed.items():
        if sha256(ZHENKAI_DIR / name) != digest:
            problems.append(f"public/fonts/lxgw-zhenkai/{name} no longer matches SHA256SUMS.txt")

    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    print(
        f"ok: {CSS.relative_to(ROOT)} matches the manifest; "
        f"{len(manifest['slices'])} slices present in both bands; ZhenKai manifest verified"
    )
    return 0


def write_css() -> int:
    manifest = load_manifest()
    text = css_text(manifest)
    if CSS.read_text() == text:
        print(f"unchanged: {CSS.relative_to(ROOT)}")
        return 0
    CSS.write_text(text)
    print(f"wrote {CSS.relative_to(ROOT)} ({len(manifest['slices'])} slices x 2 bands)")
    return 0


def pyftsubset() -> list[str]:
    found = shutil.which("pyftsubset")
    if found:
        return [found]
    beside = Path(sys.executable).with_name("pyftsubset")
    if beside.exists():
        return [str(beside)]
    raise SystemExit(
        "pyftsubset not found. Install fonttools and brotli first:\n"
        "  python3 -m venv .venv && .venv/bin/pip install fonttools brotli"
    )


def resolve_source_ttf(explicit: str | None) -> tuple[Path, tempfile.TemporaryDirectory | None]:
    if explicit:
        return Path(explicit).resolve(), None
    pinned = ZHENKAI_SOURCE
    scratch = tempfile.TemporaryDirectory(prefix="lxgw-zhenkai-")
    target = Path(scratch.name) / pinned["asset"]
    print(f"downloading {pinned['url']}")
    request = urllib.request.Request(pinned["url"], headers={"User-Agent": "pi-web-font-build"})
    with urllib.request.urlopen(request) as response, target.open("wb") as handle:
        shutil.copyfileobj(response, handle)
    return target, scratch


def verify_source_ttf(path: Path) -> None:
    pinned = ZHENKAI_SOURCE
    size = path.stat().st_size
    digest = sha256(path)
    if size != pinned["bytes"] or digest != pinned["sha256"]:
        raise SystemExit(
            f"{path} is not the pinned {pinned['release']} {pinned['asset']}:\n"
            f"  want {pinned['bytes']} bytes / sha256 {pinned['sha256']}\n"
            f"  got  {size} bytes / sha256 {digest}"
        )


def subset_pass(manifest: dict, ttf: Path) -> int:
    command = pyftsubset()
    ZHENKAI_DIR.mkdir(parents=True, exist_ok=True)

    def build(entry: dict) -> Path:
        target = ZHENKAI_DIR / f"{ZHENKAI_PREFIX}{entry['subset']}.woff2"
        subprocess.run(
            [
                *command,
                str(ttf),
                f"--unicodes={','.join(entry['unicodeRange'].split())}",
                "--flavor=woff2",
                "--ignore-missing-unicodes",
                f"--output-file={target}",
            ],
            check=True,
            capture_output=True,
        )
        return target

    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
        written = list(pool.map(build, manifest["slices"]))

    total = sum(path.stat().st_size for path in written)
    print(f"wrote {len(written)} subsets to {ZHENKAI_DIR.relative_to(ROOT)} ({total / 1024 / 1024:.1f} MiB)")
    return 0


def write_sums(manifest: dict) -> int:
    names = sorted(f"{ZHENKAI_PREFIX}{entry['subset']}.woff2" for entry in manifest["slices"])
    lines = [f"{sha256(ZHENKAI_DIR / name)}  {name}" for name in names]
    (ZHENKAI_DIR / "SHA256SUMS.txt").write_text("\n".join(lines) + "\n")
    print(f"wrote public/fonts/lxgw-zhenkai/SHA256SUMS.txt ({len(lines)} entries)")
    return 0


def subsets(explicit_ttf: str | None) -> int:
    manifest = load_manifest()
    ttf, scratch = resolve_source_ttf(explicit_ttf)
    try:
        verify_source_ttf(ttf)
        subset_pass(manifest, ttf)
    finally:
        if scratch:
            scratch.cleanup()
    write_sums(manifest)
    return check()


def write_manifest_from(source: Path) -> int:
    """Bootstrap/refresh the slice list from a stylesheet that declares it."""
    existing = load_manifest() if MANIFEST.exists() else {}
    slices = slices_from(source.read_text(), "lxgw-wenkai-screen")
    manifest = {
        "note": (
            "Generated by scripts/build-content-cjk-fonts.py --slices-from. The unicode-range "
            "list is the WenKai Screen webfont's subsetting; the ZhenKai subsets are cut from the "
            "same ranges so both weight bands fetch matching slices."
        ),
        "family": FAMILY,
        "wenkai": WENKAI_SOURCE,
        "zhenkai": ZHENKAI_SOURCE,
        "slices": slices,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=1) + "\n")
    previous = len(existing.get("slices", []))
    print(f"wrote {MANIFEST.relative_to(ROOT)}: {len(slices)} slices (was {previous})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify the committed output against the manifest")
    parser.add_argument("--css", action="store_true", help="rewrite app/fonts-content-cjk.css")
    parser.add_argument("--subsets", action="store_true", help="rebuild public/fonts/lxgw-zhenkai/")
    parser.add_argument("--all", action="store_true", help="--css plus --subsets")
    parser.add_argument("--ttf", help="use this LXGWZhenKaiGB-Regular.ttf instead of downloading it")
    parser.add_argument("--slices-from", metavar="CSS", help="rewrite the manifest's slice list from a WenKai stylesheet")
    args = parser.parse_args()

    if args.slices_from:
        return write_manifest_from(Path(args.slices_from))
    if args.all:
        return write_css() or subsets(args.ttf)
    if args.subsets:
        return subsets(args.ttf)
    if args.css:
        return write_css()
    return check()


if __name__ == "__main__":
    sys.exit(main())
